### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by alhafidzhamdan** [epi2me-labs/fastcat#1]
Hi there,
How do I install a working copy of fastcat on my linux system?
Is it on conda yet?
Thanks in advance!
A

**Comment by cjw85** [comment]
Fastcat is indeed available on conda through our own channel:

    conda install -c epi2melabs fastcat

We apologise that there's no instructions in the README, that was a bit of an oversight!

**Comment by alhafidzhamdan** [comment]
Great! Thanks so much! A
