### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by OSAGSoliman** [epi2me-labs/fastcat#2]
Hello,

I am try to install fastcat through conda install -c epi2melabs fastcat and it give me the following error:

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/epi2melabs/linux-64/fastcat-0.4.10-h9bf148f_0.tar.bz2>
Elapsed: 00:00.210166
CF-RAY: 72dbba171d8f5fcb-MRS

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

is there any way to fix this error?
Also, i tried the recommended way using: mamba create -n fastcat -c conda-forge -c epi2melabs fastcat

it give the following error:

Traceback (most recent call last):
  File "/home/genomics/anaconda3/bin/mamba", line 11, in <module>
    sys.exit(main())
  File "/home/genomics/anaconda3/lib/python3.8/site-packages/mamba/mamba.py", line 848, in main
    from conda.common.compat import ensure_text_type, init_std_stream_encoding
ImportError: cannot import name 'init_std_stream_encoding' from 'conda.common.compat' (/home/genomics/anaconda3/lib/python3.8/site-packages/conda/common/compat.py)

**Comment by SamStudio8** [comment]
Hi @OSAGSoliman, we are currently observing this error in our own test system and believe it is an intermittent issue with the conda content delivery network. Retrying the installation should eventually work.

**Comment by OSAGSoliman** [comment]
Thank you, that was perfect.
