### ISSUE TITLE
Error executing process > 'fastcat (1)'

### ISSUE THREAD

**Issue by JISC1008** [epi2me-labs/fastcat#3]
Instance parameters
{
  fastq: /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/44ea73db01058139d03114c2c973956f0331ab0d0328ce6bcc907b73c518c322/5051b9327cc3758e2e77575f824b6b65db8c48aa2b4852e7b7194f7708d51484/4697b90ec163125268b16f16842267e75092c7d394bde65a46172d37cb218098/minION/FirstRun_151222/basecalling/pass,
  classifier: kraken2,
  batch_size: 1000,
  analyse_unclassified: true,
  database_set: ncbi_16s_18s,
  store_dir: /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/44ea73db01058139d03114c2c973956f0331ab0d0328ce6bcc907b73c518c322/5051b9327cc3758e2e77575f824b6b65db8c48aa2b4852e7b7194f7708d51484/4697b90ec163125268b16f16842267e75092c7d394bde65a46172d37cb218098/AppData/Local/EPI2MELabs/app-4.1.3/store_dir,
  bracken_level: S,
  port: 8080,
  host: localhost,
  out_dir: /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/44ea73db01058139d03114c2c973956f0331ab0d0328ce6bcc907b73c518c322/5051b9327cc3758e2e77575f824b6b65db8c48aa2b4852e7b7194f7708d51484/e01dbf34c0ac1f05f59d59abea2aeec8f0e81f0e3c205abe7bfde884e1c801c4/instances/wf-metagenomics_42bf296e-208a-4a2b-b168-a74c17632fcc/output,
  threads: 2,
  server_threads: 2,
  kraken_clients: 2,
  wf: {
    agent: epi2melabs/4.1.3
  }
}

Stopped with error
epi2me-labs/wf-metagenomics
v2.2.0

Nextflow workflow report
[blissful_bassi]
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 125.

The full error message was:

Error executing process > 'fastcat (1)'

Caused by:
  Process `fastcat (1)` terminated with an error exit status (125)

Command executed:

  mkdir fastcat_stats
  fastcat             -s pass             -r fastcat_stats/per-read-stats.tsv             -f fastcat_stats/per-file-stats.tsv                          pass             | bgzip -@ 2 > seqs.fastq.gz

Command exit status:
  125

Command output:
  (empty)

Command error:
  docker: Error response from daemon: mount /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/44ea73db01058139d03114c2c973956f0331ab0d0328ce6bcc907b73c518c322/5051b9327cc3758e2e77575f824b6b65db8c48aa2b4852e7b7194f7708d51484 to /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/eb90df73f871badc59f5ae0ac15bf809577b236b6a6de32cf9fc95197acf2322: no space left on device.
  See 'docker run --help'.

Work dir:
  /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/44ea73db01058139d03114c2c973956f0331ab0d0328ce6bcc907b73c518c322/5051b9327cc3758e2e77575f824b6b65db8c48aa2b4852e7b7194f7708d51484/e01dbf34c0ac1f05f59d59abea2aeec8f0e81f0e3c205abe7bfde884e1c801c4/instances/wf-metagenomics_42bf296e-208a-4a2b-b168-a74c17632fcc/work/38/d1bbe1aad01f9883f6f734bd980522

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by cjw85** [comment]
This is not an error with fastcat:

```
Command error:
docker: Error response from daemon: mount /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/44ea73db01058139d03114c2c973956f0331ab0d0328ce6bcc907b73c518c322/5051b9327cc3758e2e77575f824b6b65db8c48aa2b4852e7b7194f7708d51484 to /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/eb90df73f871badc59f5ae0ac15bf809577b236b6a6de32cf9fc95197acf2322: no space left on device.
See 'docker run --help'.
```

is fairly transparent --- your docker container mount ran out of disk space.
