### ISSUE TITLE
Error: Cannot create output directory 'fastcat-histograms'. Check location is writeable and directory does not exist.

### ISSUE THREAD

**Issue by Rohit-Satyam** [epi2me-labs/fastcat#6]
Fastcat gives me the error for not being able to overwrite the `fastcat-histograms` directory so I have to remove it when executing it on multiple directories. Can this be fixed?

```
ls -1 -d ../*/ | while read p; do name=$(echo $p | xargs -n 1 basename); fastcat -x $p -f ${name}.txt -a 100 > ${name}.fastq; rm -rf fastcat-histograms/; done
```

right now tackling this while removing this directory after every iteration.

**Comment by cjw85** [comment]
This is the intended behaviour to prevent overwriting or deleting previous results. See the CLI help for how to change the output directory.
